name: Dowload artifact

inputs:
  workflow:
    required: true
  artifact:
    required: true
  dir:
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Download artifact'
      uses: actions/github-script@v7
      with:
        script: |
          let allRuns = await github.rest.actions.listWorkflowRuns({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: "${{ inputs.workflow }}.yml",
            status: "success",
            per_page: 1
          });
          let run = allRuns.data.workflow_runs[0];
          let allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: run.id
          });
          let matchArtifact = allArtifacts.data.artifacts.filter((artifact) => {
            return artifact.name == "${{ inputs.artifact }}"
          })[0];
          let download = await github.rest.actions.downloadArtifact({
            owner: context.repo.owner,
            repo: context.repo.repo,
            artifact_id: matchArtifact.id,
            archive_format: 'zip',
          });
          let fs = require('fs');
          fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${{ inputs.artifact }}.zip`, Buffer.from(download.data));

    - name: 'Unzip artifact'
      shell: bash
      run: |
        unzip "${{ inputs.artifact }}.zip" -d "${{ inputs.dir }}"
        rm ${{ inputs.artifact }}.zip
